### ISSUE TITLE
Latency is overriden when response is cached

### ISSUE THREAD

**Issue by trondrensel** [promptfoo/promptfoo#980] opened 2024-06-21 08:12 UTC
<img width="770" alt="Skjermbilde 2024-06-21 kl  10 09 43" src="https://github.com/promptfoo/promptfoo/assets/158487250/54441310-77f6-4814-b64f-97e09c2e7489">

When a test uses cached results, the latency is currently set to that of the most recent run with cached data. 
Ideally, the latency should reflect the value from the original execution when the results were first generated.

**Comment by mldangelo** [comment] 2024-06-28 20:55
Thank you for filing this @trondrensel Latency caching is going into our backlog. This is a duplicate of https://github.com/promptfoo/promptfoo/issues/945 We can track progress there!

**Closed by mldangelo** 2024-06-28 20:55 UTC
Labels: enhancement
