### ISSUE TITLE
Alternative to Nunjucks?

### ISSUE THREAD

**Issue by therealpaulgg** [promptfoo/promptfoo#92] opened 2023-07-26 18:12 UTC
One issue I've encountered frequently with Nunjucks is that because it is designed to work with HTML templating, it by default really wants to add HTML-escaped characters to anything it templates.

For example:

```yaml
- role: system
  content: |
    You are a helpful assistant which suggests users healthy snacks to purchase

- role: user
  content: '{{ request }}'
```

For the 'request' variable, nunjucks will HTML escape any characters that are deemed sensitive. Just a couple of examples:
- '<' becomes '&lt'
- '>' becomes '&gt'
- '"' becomes '&quot'

Given the general sensitivity of LLMs, I'd like to ensure prompts in general are as close to natural language as possible. I have noticed greater quality outputs the more natural language is used.

We can use the 'safe' keyword in some circumstances but not all. For example trying to use 'safe' in the above example could result in a malformed YAML file.

Trying to think of perhaps a specific templating alternative for YAML..

**Comment by typpo** [comment] 2023-07-27 06:02
The pattern that I've been using is `{{ varname | dump | safe}}`, which will quote the string accordingly.

```yaml
- role: user
  content: {{ request | dump | safe }}
```

Maybe this needs to be more prominent in the examples?

**Comment by farzadab** [comment] 2023-08-08 17:38
@typpo Not sure if I understood what you're suggesting, but the issue is not just for YAML (I'm not using YAML anywhere and I still hit the "escaping" issue). IMO the tool shouldn't change the prompt in any way as LLMs are quite sensitive to such alterations.

**Comment by typpo** [comment] 2023-08-08 18:39
The above answer applies to any prompt template (yaml, json, or plaintext).  But in #101 I have disabled nunjucks autoescaping, which should largely solve this problem.  Will be in the next release!

**Comment by farzadab** [comment] 2023-08-08 18:39
Perfect!

**Closed** 2023-08-08 18:43 UTC
