### ISSUE TITLE
prompt does not support '/' in question

### ISSUE THREAD

**Issue by landhu** [promptfoo/promptfoo#1064] opened 2024-07-02 12:49 UTC
C:\Users\AppData\Roaming\npm\node_modules\promptfoo\dist\src\prompts\index.js:136
            throw new Error(`There are no prompts in ${JSON.stringify(prompt.raw)}`);
                  ^

Error: There are no prompts in "How many AR/VR devices xxxxx?"
    at readPrompts (C:\Users\AppData\Roaming\npm\node_modules\promptfoo\dist\src\prompts\index.js:136:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfigs (C:\Users\AppData\Roaming\npm\node_modules\promptfoo\dist\src\main.js:129:27)
    at async runEvaluation (C:\Users\AppData\Roaming\npm\node_modules\promptfoo\dist\src\main.js:545:48)
    at async Command.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\promptfoo\dist\src\main.js:704:9)

Node.js v20.15.0

**Comment by mldangelo** [comment] 2024-07-02 15:05
Thanks for reporting this issue, @landhu. I apologize for the trouble you're experiencing. I believe this is a duplicate of [issue #1063](https://github.com/promptfoo/promptfoo/issues/1063) and is related to your prompt file path. I am addressing the path issue in [PR #1066](https://github.com/promptfoo/promptfoo/pull/1066), which I'll get deployed later today. Please let me know if it doesn't resolve the issue for you. Thanks for your patience and for bringing this to our attention!

**Comment by mldangelo** [comment] 2024-07-02 20:28
A fix for this was deployed in [0.68.1](https://github.com/promptfoo/promptfoo/releases/tag/0.68.1) Please let me know if you run into any other issues and thanks again for reporting it!

**Closed by mldangelo** 2024-07-02 20:28 UTC
