### ISSUE TITLE
Install promptfoo on kubernetes

### ISSUE THREAD

**Issue by rrbanda** [promptfoo/promptfoo#1252] opened 2024-07-24 03:31 UTC
Run promptfoo on a container platform by using the following step that will build an image is not working . 

While using import from git strategy it was able to build and push the image , however the pod that runs promptfoo is showing error in the log as shared below 

Need to identify the change that are required so it can run on a kubernetes cluster

**Comment by rrbanda** [comment] 2024-07-24 03:49
```
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/.npm/_cacache/tmp/de2575e0
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1005900000:0 "/opt/app-root/src/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

**Comment by rrbanda** [comment] 2024-07-24 03:58
<img width="1040" alt="Screenshot 2024-07-23 at 11 57 52 PM" src="https://github.com/user-attachments/assets/ad0b4f89-cf64-49e8-b1e9-a5ad5c4d0ab9">

**Comment by typpo** [comment] 2024-07-24 07:22
Hey @rrbanda, thanks for the report. I think this has to do with how k8s handles permissions.  I have a potential fix in #1257, although I have not tried it on k8s myself.  If you can give it a try and let me know, that would be great.

**Comment by mldangelo** [comment] 2024-07-24 19:05
@rrbanda We just cut a release with the new docker image. I also confirmed that I can run it ok k8s. Please check it out and let us know if you run into any other issues.

**Comment by rrbanda** [comment] 2024-07-24 19:08
@mldangelo thank you , do you have any docs or link to image ? i can try deploying and share feedback

**Comment by rrbanda** [comment] 2024-07-24 19:08
or i need to build and push image from promptfoo git repo on my end ?

**Comment by mldangelo** [comment] 2024-07-24 19:14
@rrbanda you can check out the library and build from source. I'll work on getting an image published for you today.

**Comment by rrbanda** [comment] 2024-07-24 19:38
@mldangelo just deployed with newly built image from source but still getting an error while the pod is getting created 
<img width="1163" alt="Screenshot 2024-07-24 at 3 37 15 PM" src="https://github.com/user-attachments/assets/193d02f4-65a4-4de5-8f16-aa6f86427d3d">

**Comment by mldangelo** [comment] 2024-07-24 19:40
@rrbanda what's in `docker-entrypoint.sh`?  Our dockerfile creates `entrypoint.sh`. Did you create your own?

**Comment by rrbanda** [comment] 2024-07-24 19:43
@mldangelo i have not created one but is it generated as part of the build process ?

**Comment by rrbanda** [comment] 2024-07-24 19:51
i tried a different way and still got an error 
<img width="1163" alt="Screenshot 2024-07-24 at 3 37 15 PM" src="https://github.com/user-attachments/assets/cce6b114-cb54-40fa-aa60-757f5e60e493">

**Comment by didlawowo** [comment] 2024-08-23 05:54
is there a helm chart for promptfoo ?

**Comment by mldangelo** [comment] 2024-08-25 03:05
> is there a helm chart for promptfoo ?

@tamdoEH authored [this Helm chart for promptfoo](https://github.com/tamdoEH/promptfoo-helm). Note that I haven't tested it yet. If either of you (@didlawowo or @tamdoEH) would be open to contributing it directly into promptfoo — whether by working on a pull request, testing, or providing feedback - we’d greatly appreciate the help.

**Comment by mldangelo** [comment] 2024-10-01 06:21
Hi @rrbanda, thanks again for your patience and for all the feedback along the way. Since we’ve made several updates to the Docker image and there’s been some progress on Kubernetes support, I’m going to close this issue.

If you’re still running into issues or need further assistance, feel free to reopen the issue or start a new one. Also, a community-contributed Helm chart can be found here: [Gekko0114/kube-promptfoo-controller](https://github.com/Gekko0114/kube-promptfoo-controller) if that’s helpful for your setup.

We really appreciate your help in improving promptfoo!

**Closed by mldangelo** 2024-10-01 06:21 UTC
